services:
  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./secrets/.env.postgrest
    # NO external ports - internal only for security
    networks:
      - chattterbox-network
    labels:
      # Datadog log collection
      - 'com.datadoghq.ad.logs=[{"source": "postgrest", "service": "postgrest"}]'

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80" # HTTP (for redirect to HTTPS)
      - "443:443" # HTTPS
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chattterbox-network
    depends_on:
      - postgrest
    labels:
      # Datadog log collection
      - 'com.datadoghq.ad.logs=[{"source": "caddy", "service": "caddy"}]'

  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: unless-stopped
    env_file:
      - ./secrets/.env.datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    networks:
      - chattterbox-network
    pid: host

volumes:
  caddy_data:
  caddy_config:

networks:
  chattterbox-network:
    driver: bridge
