services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    env_file:
      - ./secrets/.env.gateway
    networks:
      - chattterbox-network
    depends_on:
      - postgrest
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "gateway", "service": "gateway"}]'
  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/backups:/backups
    networks:
      - chattterbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "postgres", "service": "postgres"}]'
  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./secrets/.env.postgrest
    # NO external ports - internal only for security
    networks:
      - chattterbox-network
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      # Datadog log collection
      - 'com.datadoghq.ad.logs=[{"source": "postgrest", "service": "postgrest"}]'

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80" # HTTP (for redirect to HTTPS)
      - "443:443" # HTTPS
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chattterbox-network
    depends_on:
      - gateway
      - files
      - swaggerui
    labels:
      # Datadog log collection
      - 'com.datadoghq.ad.logs=[{"source": "caddy", "service": "caddy"}]'

  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: unless-stopped
    env_file:
      - ./secrets/.env.datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    networks:
      - chattterbox-network
    pid: host

  files:
    build:
      context: .
      dockerfile: ./files/Dockerfile
    container_name: files
    restart: unless-stopped
    ports:
      - "9090:9090"
    env_file:
      - ./secrets/.env.files
    networks:
      - chattterbox-network
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "files", "service": "files"}]'

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker
    restart: unless-stopped
    env_file:
      - ./secrets/.env.worker
    networks:
      - chattterbox-network
    depends_on:
      postgrest:
        condition: service_started
      postgres:
        condition: service_healthy
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "worker", "service": "worker"}]'

  swaggerui:
    image: swaggerapi/swagger-ui:latest
    container_name: swaggerui
    restart: unless-stopped
    environment:
      URL: /openapi.json
    networks:
      - chattterbox-network
    depends_on:
      - gateway
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "swaggerui", "service": "swaggerui"}]'

volumes:
  caddy_data:
  caddy_config:
  postgres_data:

networks:
  chattterbox-network:
    driver: bridge
