services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    env_file:
      - ./secrets/.env.gateway
    networks:
      - chattterbox-network
    depends_on:
      - postgrest
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "gateway", "service": "gateway"}]'
  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./secrets/.env.postgrest
    environment:
      # Enable verbose logging to capture more request details
      - PGRST_LOG_LEVEL=info
    # NO external ports - internal only for security
    networks:
      - chattterbox-network
    labels:
      # Datadog log collection with enhanced parsing
      - 'com.datadoghq.ad.logs=[{"source": "postgrest", "service": "postgrest", "log_processing_rules": [{"type": "include_at_match", "name": "include_request_logs", "pattern": "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}.*HTTP"}]}]'

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80" # HTTP (for redirect to HTTPS)
      - "443:443" # HTTPS
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chattterbox-network
    depends_on:
      - gateway
      - files
    labels:
      # Datadog log collection
      - 'com.datadoghq.ad.logs=[{"source": "caddy", "service": "caddy"}]'

  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: unless-stopped
    env_file:
      - ./secrets/.env.datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    networks:
      - chattterbox-network
    pid: host

  files:
    build:
      context: .
      dockerfile: ./files/Dockerfile
    container_name: files
    restart: unless-stopped
    ports:
      - "9090:9090"
    env_file:
      - ./secrets/.env.files
    networks:
      - chattterbox-network
    labels:
      - 'com.datadoghq.ad.logs=[{"source": "files", "service": "files"}]'

volumes:
  caddy_data:
  caddy_config:

networks:
  chattterbox-network:
    driver: bridge
